### ISSUE TITLE
Editor: Toolbar Layout error with i18n.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#15134]
#### Editor's element `#toolbar button` has simple layout error, `#toolbar button` is heighter than before.

![image](https://user-images.githubusercontent.com/23699926/47499003-6d469580-d891-11e8-943e-28a1b598276e.png)

##### Three.js version

- [x] r98Dev

##### Browser

- [x] Chrome 70
- [x] Firefox 63

##### OS

- [x] Windows 7

---

#### I fixed it by this way.

```css
	/* ProjectDir\editor\css\light.css  row 214 */
	#toolbar button {
		margin-right: 6px;
		line-height: 14px; /* new */
		height: 24px;; /* new */
	}
```
##### Bugfixed result:
![image](https://user-images.githubusercontent.com/23699926/47498558-286e2f00-d890-11e8-9223-b076e69c68ec.png)
