### ISSUE TITLE
the lastest version editor ,when we drag the draggable element, the viewport become empty

### ISSUE THREAD

**Issue by Frankling** [mrdoob/three.js#24794]
![微信图片_20221014101734](https://user-images.githubusercontent.com/5674121/195746926-0a557992-de59-462a-94a7-909089c893f9.png)

**Comment by Mugen87** [comment]
I can reproduce. It also happens with `dev` and earlier versions of the editor (e.g. with `r130`). 

However, the glitch only appears in Chrome 106.0.5249.119. Chrome Canary is working fine as well as Firefox. So maybe it's a browser issue that has already been fixed.

**Comment by EstebanFuentealba** [comment]
Add following css style as a workaround fix

```css
[draggable="true"] {
  transform: translate(0, 0);
  z-index: 0;
}
```
